language: java
env:
  global:
  - SONATYPE_USERNAME=mihxil
  - secure: KLMj2p2CSG254RqBlPMLZZ2uHbGz1B+Bwul7rqVw8XOYOnSesHgaZmEGFOnEmpoPJFkNMldMGeTmMExrDuLjbdPxbarA0zit8etyJ+eM8cmHEef7gA0CM0inwJsW5ilyDWrLMxizXg3pGDsLWyXmuGiL5Th4Q2A38mYmBfTnlq0T0uyRjDsI/f7/bn0gPLIyICrVQkgYzjBVmh5tWKqZ3Vr4FSkuI2idtFSAvYrY2OHm5GtqwA0NlyYM6W2FsiFtWvDX+Ws6Fph1xcdmO0YBmXCWSmALkQ3syt/K/V76qVITXPgLYfNwgZCFKquxDb6W0vrH/9Xv+aW0TqtzNj3CNwh7dkEpW0F3XWxuxWX5rhmFEIh0ev51ER9CcguSDD7yDLl1ChhRmOROajfFQ2nwQIo8JJeaW1SOjMK5yID7i2xlNtUXzUjKFR+lrmTuyA1U+MK6i6oK6x0i0x7kNZaVj7Ba4poM+KugcqqATr8Swz6tn9BJ+46KcrxfFEplm+2YmYm1A3vyAMEZqq/WuVja+ukcIYCa/0PgKOBR/kgMv3UHwgVYWgQNlli6D10RXmQ181vtOzFt0J2nN65JqZegq0ucPJdyPjHwwGaumIjH/XMXnbYiNNcC9eIEC8jhsM+wQzZ8kpo6AdJnY7GXAfDAii5dOT2goyYeZG4+qVmTMuQ=
jdk:
- oraclejdk8
sudo: false
script: mvn clean test install
after_success:
- mvn -Pdeploy deploy --settings travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
