language: java
env:
  global:
  - SONATYPE_USERNAME=mihxil
  - secure: UgcYkeZrcsaXN0hrU56afunymKRCNxZW1mGf/QCBwQBfjNErmZefL1/BTLAdYTzzlE+QiGIDxF3USBUhm90/MNyb5de+48oBF7f04U99fUppn9VIesModrxNqrJASlkT1IAR5IFJi2ixFUVwC9RkCkBNJzIbw514xoL5qzHCW668uYTntnozqgdj/HwtlqecnjJsp9fnb8JDNdoFuNqSZxZvHTMqxDsffBjtvVr1C/4hkwcEubSy4hrBGxORA68fytFv+OvYrGUrksr5sFfPBbPMvqFg5yRjhzd1mxClN29zPJj4SZ0jG0uILGhnwXsf78y9/dtW3gdpUWVW6lkYSGTt3FIekpYcnziew9/zdia9vz0Xl2yiO2I4+niRoEIZvQstvrlKtI2uvszffHFsh8raX1n/AsWhzEctuqI11OEe0wUV48bzAYyZkmtU3K1iNxR577twITJFp99OWtetx37On+GMAPg/oSekq11Xl13I7MqMukS3+cvnCuzUUIq2Iiaq5oQozRDnQPx/k1oC0g3O3WMyMQLTB//ZwD+hvXzkH+1+AYZ/CTqnBtkQ/cyZAbqwqPisuC720lVSmAH6wdE+BknL5ihwxaVZVZ4GrV2G3yHDcna3JU6ie1bTsYaDAxsgzxGU2BUSxRjf1qODfaclGdL5vxpTi/q/0xYIXZA=
jdk:
- oraclejdk8
sudo: false
script: mvn clean test install
after_success:
- mvn -Pdeploy deploy --settings travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
